#!/usr/bin/env python3
"""Build KG page with separate data files - no quote escaping hell."""
import json

with open('data/star_tree.json','r',encoding='utf-8') as f: tree=json.load(f)
with open('data/cross_book_events.json','r',encoding='utf-8') as f: cross=json.load(f)
with open('data/astrology.json','r',encoding='utf-8') as f: astro=json.load(f)

# Write data JS files
with open('docs/kg/kg_tree_data.js','w',encoding='utf-8') as f:
    f.write('window.KG_TREE='); json.dump(tree,f,ensure_ascii=False); f.write(';')
with open('docs/kg/kg_cross_data.js','w',encoding='utf-8') as f:
    f.write('window.KG_CROSS='); json.dump(cross,f,ensure_ascii=False); f.write(';')
with open('docs/kg/kg_astro_data.js','w',encoding='utf-8') as f:
    f.write('window.KG_ASTRO='); json.dump(astro,f,ensure_ascii=False); f.write(';')

html_parts = []
a = html_parts.append

a('<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n<meta charset="UTF-8">\n')
a('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
a('<title>知识图谱 - 星庐</title>\n')
a('<link rel="stylesheet" href="../css/style.css">\n<style>\n')
a('body{background:var(--bg-deepest);color:var(--text-body);font-family:var(--font-sans);margin:0}\n')
a('.main{max-width:1400px;margin:0 auto;padding:20px}\n')
a('h1{color:var(--accent-gold);font-family:var(--font-serif);text-align:center;margin-bottom:4px}\n')
a('h2{color:var(--accent-gold);font-size:1.1rem;margin:24px 0 12px;border-bottom:1px solid var(--border);padding-bottom:8px}\n')
a('.tabs{display:flex;gap:0;justify-content:center;margin:16px 0}\n')
a('.tabs button{padding:10px 24px;border:1px solid var(--border);background:var(--bg-card);color:var(--text-body);cursor:pointer;font-size:0.9rem}\n')
a('.tabs button:first-child{border-radius:6px 0 0 6px}\n')
a('.tabs button:last-child{border-radius:0 6px 6px 0}\n')
a('.tabs button.on{background:var(--accent-gold);color:#0a0e1a;border-color:var(--accent-gold)}\n')
a('.panel{display:none}.panel.on{display:block}\n')
a('.tree{font-size:0.85rem;line-height:1.8}\n')
a('.tree ul{list-style:none;padding-left:24px}\n')
a('.tree li{position:relative}\n')
a('.tree li::before{content:"";position:absolute;left:-16px;top:10px;width:12px;height:1px;background:var(--border)}\n')
a('.tree li::after{content:"";position:absolute;left:-16px;top:0;bottom:0;width:1px;background:var(--border)}\n')
a('.tree li:last-child::after{height:10px}\n')
a('.tree .node{cursor:pointer;color:var(--text-body);transition:color 0.2s;display:inline-block;padding:2px 6px;border-radius:4px}\n')
a('.tree .node:hover{color:var(--accent-gold);background:rgba(201,169,110,0.1)}\n')
a('.tree .node.folder{font-weight:600;color:var(--accent-warm)}\n')
a('.tree .node.desc{font-size:0.75rem;color:var(--text-muted);margin-left:8px}\n')
a('.tree .collapsed>ul{display:none}\n')
a('.xb-item{padding:12px 16px;margin-bottom:8px;background:var(--bg-card);border:1px solid var(--border);border-radius:6px}\n')
a('.xb-head{display:flex;align-items:center;gap:12px;margin-bottom:6px}\n')
a('.xb-year{font-weight:700;color:var(--accent-gold);min-width:70px}\n')
a('.xb-type{padding:2px 10px;border-radius:10px;font-size:0.75rem;color:#fff}\n')
a('.xb-sources{font-size:0.75rem;color:var(--text-muted)}\n')
a('.xb-text{font-size:0.82rem;line-height:1.6;color:var(--text-muted);padding-left:22px;cursor:pointer}\n')
a('.xb-text:hover{color:var(--accent-gold)}\n')
a('.xb-omen{color:var(--accent-gold);font-size:0.78rem;display:inline-block;margin-top:2px}\n')
a('.as-item{padding:10px 14px;margin-bottom:6px;background:var(--bg-card);border:1px solid var(--border);border-radius:6px;display:flex;gap:12px;align-items:flex-start}\n')
a('.as-type{min-width:60px;padding:2px 8px;border-radius:10px;font-size:0.72rem;color:#fff;text-align:center}\n')
a('.as-consequence{font-size:0.82rem;line-height:1.5;flex:1}\n')
a('.as-source{font-size:0.7rem;color:var(--text-muted)}\n')
a('.e-solar{background:#B33A3A}.e-lunar{background:#5B3A7A}.e-comet{background:#3A6B5A}\n')
a('.e-meteor{background:#7A5B3A}.e-encroach{background:#8B4513}\n')
a('</style>\n</head>\n<body>\n')
a('<nav class="top-nav"><div class="nav-inner">\n')
a('<a href="../index.html" class="nav-logo">&#9737; 星庐</a>\n')
a('<div class="nav-links">\n')
a('<a href="../index.html">首页</a><a href="../search.html">搜索</a>\n')
a('<a href="../kg/timeline.html">天象事件</a><a href="../kg/starmap.html">古星图</a>\n')
a('<a href="../kg/network.html">知识图谱</a></div>\n')
a('</div></nav>\n')
a('<div class="main">\n<h1>知识图谱</h1>\n')
a('<div class="tabs">\n')
a('<button class="on" onclick="showTab(\'tree\')">星官谱系</button>\n')
a('<button onclick="showTab(\'cross\')">跨书关联 ('+str(len(cross))+')</button>\n')
a('<button onclick="showTab(\'astro\')">占星对应 ('+str(len(astro))+')</button>\n')
a('</div>\n')
a('<div class="panel on" id="panel-tree"><h2>中国星官体系</h2><div class="tree" id="tree"></div></div>\n')
a('<div class="panel" id="panel-cross"><h2>跨书天象验证</h2><div id="cross-list"></div></div>\n')
a('<div class="panel" id="panel-astro"><h2>占星对应</h2><div id="astro-list"></div></div>\n')
a('</div>\n')

# JS
a('<script src="kg_tree_data.js"></script>\n')
a('<script src="kg_cross_data.js"></script>\n')
a('<script src="kg_astro_data.js"></script>\n')
a('<script>\n')
a('var T={solar_eclipse:"日食",lunar_eclipse:"月食",comet:"彗星",meteor:"流星",guest_star:"客星",encroach:"星犯",guard:"星守",occult:"星掩",entry:"星入",conjunction:"星合",clustering:"星聚",day_visible:"昼见"};\n')
a('var C={solar_eclipse:"e-solar",lunar_eclipse:"e-lunar",comet:"e-comet",meteor:"e-meteor",encroach:"e-encroach"};\n')
a('function esc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML;}\n')
a('function showTab(n){\n')
a(' document.querySelectorAll(".tabs button").forEach(function(b){b.classList.remove("on")});\n')
a(' event.target.classList.add("on");\n')
a(' document.querySelectorAll(".panel").forEach(function(p){p.classList.remove("on")});\n')
a(' document.getElementById("panel-"+n).classList.add("on");\n')
a('}\n')

# Tree
a('function renderTree(node,container,depth){\n')
a(' var ul=document.createElement("ul");container.appendChild(ul);\n')
a(' (node.children||[]).forEach(function(child){\n')
a('  var li=document.createElement("li");\n')
a('  var s=document.createElement("span");s.className="node";\n')
a('  if(child.children&&child.children.length>0){\n')
a('   s.className+=" folder";s.textContent=(depth===0?"● ":"")+child.name;\n')
a('   if(child.description){var d=document.createElement("span");d.className="node desc";d.textContent=" \u2014 "+child.description;s.appendChild(d);}\n')
a('   s.onclick=function(e){e.stopPropagation();this.parentElement.classList.toggle("collapsed");};\n')
a('   li.appendChild(s);renderTree(child,li,depth+1);\n')
a('  }else{\n')
a('   s.textContent=child.name;\n')
a('   if(child.description){var d=document.createElement("span");d.className="node desc";d.textContent=" \u2014 "+child.description;s.appendChild(d);}\n')
a('   if(child.stars){var st=document.createElement("span");st.className="node desc";st.textContent=" \u2605 "+child.stars;s.appendChild(st);}\n')
a('   li.appendChild(s);\n')
a('  }\n')
a('  ul.appendChild(li);\n')
a(' });\n')
a('}\n')
a('renderTree(window.KG_TREE,document.getElementById("tree"),0);\n')

# Cross
a('var cl=document.getElementById("cross-list");\n')
a('window.KG_CROSS.forEach(function(cb){\n')
a(' var y=cb.year<0?"\u524d"+(-cb.year):""+cb.year;\n')
a(' var h="<div class=\\"xb-item\\">";\n')
a(' h+="<div class=\\"xb-head\\"><span class=\\"xb-year\\">"+y+"</span><span class=\\"xb-type "+(C[cb.type]||"")+"\\">"+(T[cb.type]||cb.type)+"</span><span class=\\"xb-sources\\">"+cb.sources.length+"\u90e8\u53f2\u4e66\uff1a"+cb.sources.join(", ")+"</span></div>";\n')
a(' cb.events.forEach(function(ev){\n')
a('  var u=ev.url||"";\n')
a('  h+="<div class=\\"xb-text\\" onclick=\\"if(this.dataset.url)window.open(this.dataset.url);\\" data-url=\\""+u+"\\">"+esc(ev.description)+" <small>("+ev.source+")</small>";\n')
a('  if(ev.omen) h+=" <span class=\\"xb-omen\\">"+esc(ev.omen)+"</span>";\n')
a('  h+="</div>";\n')
a(' });\n')
a(' h+="</div>";\n')
a(' cl.innerHTML+=h;\n')
a('});\n')

# Astro
a('var al=document.getElementById("astro-list");\n')
a('window.KG_ASTRO.forEach(function(a){\n')
a(' var h="<div class=\\"as-item\\">";\n')
a(' h+="<span class=\\"as-type "+(C[a.type]||"")+"\\">"+(T[a.type]||a.type)+"</span>";\n')
a(' h+="<div class=\\"as-consequence\\">"+esc(a.consequence)+"</div>";\n')
a(' h+="<div class=\\"as-source\\">"+esc(a.source)+"</div>";\n')
a(' h+="</div>";\n')
a(' al.innerHTML+=h;\n')
a('});\n')
a('</script>\n</body>\n</html>')

html = ''.join(html_parts)
with open('docs/kg/network.html', 'w', encoding='utf-8') as f:
    f.write(html)
print('Saved:', len(html), 'bytes')
